In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

https://www.data.gouv.fr/datasets/demandes-de-valeurs-foncieres?resource_id=087ec735-74fd-48a7-a82e-0b1cd3ea6fe9

In [2]:

# Charger les données
dvf = pd.read_csv(
    r"C:\Users\anass\Desktop\immoscout-analytics\data\raw\ValeursFoncieres-2025.txt",
    sep="|",
    low_memory=False
)



# Examiner les données DVF
print("DVF")
print(dvf.shape)
print(dvf.columns.tolist())
display(dvf.head())

DVF
(3714829, 43)
['Identifiant de document', 'Reference document', '1 Articles CGI', '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI', 'No disposition', 'Date mutation', 'Nature mutation', 'Valeur fonciere', 'No voie', 'B/T/Q', 'Type de voie', 'Code voie', 'Voie', 'Code postal', 'Commune', 'Code departement', 'Code commune', 'Prefixe de section', 'Section', 'No plan', 'No Volume', '1er lot', 'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot', '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot', 'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot', 'Nombre de lots', 'Code type local', 'Type local', 'Identifiant local', 'Surface reelle bati', 'Nombre pieces principales', 'Nature culture', 'Nature culture speciale', 'Surface terrain']

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,"468000,00",NaN,NaN,NaN,B078,FARGES,1550.0,FARGES,01,158,NaN,B,815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,78.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,"468000,00",454.0,NaN,RUE,0090,DE LA REPUBLIQUE,1550.0,FARGES,01,158,NaN,B,910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.0,Dépendance,NaN,0.0,0.0,S,NaN,133.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,"468000,00",454.0,NaN,RUE,0090,DE LA REPUBLIQUE,1550.0,FARGES,01,158,NaN,B,910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,111.0,5.0,S,NaN,133.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,"180000,00",NaN,NaN,NaN,B158,LE VILLAGE,1200.0,MONTANGES,01,257,NaN,AC,334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,46.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,"180000,00",NaN,NaN,NaN,B158,LE VILLAGE,1200.0,MONTANGES,01,257,NaN,AC,338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,17.0

https://www.data.gouv.fr/datasets/carte-des-loyers-indicateurs-de-loyers-dannonce-par-commune-en-2024?resource_id=4a6074fb-7d1f-437d-8cef-f033b2114fd1

In [3]:
## Examiner les données locatives
loyers = pd.read_csv(
    r"C:\Users\anass\Desktop\immoscout-analytics\data\raw\pred-app-mef-dhup.csv",
    sep=";",
    encoding="cp1252",
    low_memory=False
)
print("LOYERS")
print(loyers.shape)
print(loyers.columns.tolist())
display(loyers.head())

LOYERS
(34960, 13)
['id_zone', 'INSEE_C', 'LIBGEO', 'EPCI', 'DEP', 'REG', 'loypredm2', 'lwr.IPm2', 'upr.IPm2', 'TYPPRED', 'nbobs_com', 'nbobs_mail', 'R2_adj']

,id_zone,INSEE_C,LIBGEO,EPCI,DEP,REG,loypredm2,lwr.IPm2,upr.IPm2,TYPPRED,nbobs_com,nbobs_mail,R2_adj
0,1,86051,Champagné-le-Sec,200070035,86,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,0,1044,"0,719908446134695"
1,1,16136,La Faye,200043016,16,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,4,1044,"0,719908446134695"
2,1,16002,Les Adjots,200043016,16,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,2,1044,"0,719908446134695"
3,1,79150,Limalonges,200069755,79,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,3,1044,"0,719908446134695"
4,1,16104,Condac,200043016,16,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,11,1044,"0,719908446134695"

In [4]:
## Examiner les données locatives
communes = pd.read_csv(
    r"C:\Users\anass\Desktop\immoscout-analytics\data\raw\v_commune_2026.csv",
    sep=",",
    low_memory=False
)
print("communes")
print(communes.shape)
print(communes.columns.tolist())
display(communes.head())

communes
(37496, 12)
['TYPECOM', 'COM', 'REG', 'DEP', 'CTCD', 'ARR', 'TNCC', 'NCC', 'NCCENR', 'LIBELLE', 'CAN', 'COMPARENT']

,TYPECOM,COM,REG,DEP,CTCD,ARR,TNCC,NCC,NCCENR,LIBELLE,CAN,COMPARENT
0,COM,01001,84.0,01,01D,012,5,ABERGEMENT CLEMENCIAT,Abergement-Clémenciat,L'Abergement-Clémenciat,0108,NaN
1,COM,01002,84.0,01,01D,011,5,ABERGEMENT DE VAREY,Abergement-de-Varey,L'Abergement-de-Varey,0101,NaN
2,COM,01004,84.0,01,01D,011,1,AMBERIEU EN BUGEY,Ambérieu-en-Bugey,Ambérieu-en-Bugey,0101,NaN
3,COM,01005,84.0,01,01D,012,1,AMBERIEUX EN DOMBES,Ambérieux-en-Dombes,Ambérieux-en-Dombes,0122,NaN
4,COM,01006,84.0,01,01D,011,1,AMBLEON,Ambléon,Ambléon,0104,NaN

In [5]:
#compter le nbr de ventes par types de bien
dvf['Type local'].value_counts(dropna=False)

Type local
NaN                                         1469244
Dépendance                                   996489
Maison                                       619955
Appartement                                  512979
Local industriel. commercial ou assimilé     116162
Name: count, dtype: int64

In [6]:
# 1. on conserve (maisons et apparts)
dvf_logements = dvf[dvf['Type local'].isin(['Maison', 'Appartement'])]

In [7]:
# 2.  affiche les lignes restantes 
print("nombre de transaction d'habitations :",len(dvf_logements))

nombre de transaction d'habitations : 1132934

In [8]:
# Combien d'habitations ont un prix manquant ou à 0 ?
dvf_logements['Valeur fonciere'] = (
    dvf_logements['Valeur fonciere']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

dvf_logements['Valeur fonciere'] = pd.to_numeric(
    dvf_logements['Valeur fonciere'],
    errors='coerce'
)
prix_invalides = dvf_logements['Valeur fonciere'].isna() | (dvf_logements['Valeur fonciere'] <= 0)

# Combien d'habitations ont une surface manquante ou à 0 ?
dvf_logements['Surface reelle bati'] = (
    dvf_logements['Surface reelle bati']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

dvf_logements['Surface reelle bati'] = pd.to_numeric(
    dvf_logements['Surface reelle bati'],
    errors='coerce'
)

surfaces_invalides = dvf_logements['Surface reelle bati'].isna() | (dvf_logements['Surface reelle bati'] <= 0)

print("Logements sans prix valide :", prix_invalides.sum())
print("Logements sans surface valide :", surfaces_invalides.sum())

C:\Users\anass\AppData\Local\Temp\ipykernel_24768\1414518120.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_logements['Valeur fonciere'] = (
C:\Users\anass\AppData\Local\Temp\ipykernel_24768\1414518120.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_logements['Valeur fonciere'] = pd.to_numeric(

Logements sans prix valide : 10448
Logements sans surface valide : 97

C:\Users\anass\AppData\Local\Temp\ipykernel_24768\1414518120.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_logements['Surface reelle bati'] = (
C:\Users\anass\AppData\Local\Temp\ipykernel_24768\1414518120.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_logements['Surface reelle bati'] = pd.to_numeric(

In [9]:
# nettoyage des donnees
dvf_clean = dvf_logements[
    (dvf_logements['Valeur fonciere'] > 0) &
    (dvf_logements['Surface reelle bati'] > 0)
]

print(len(dvf_clean))

1122389

In [10]:
# supprimer les duplicant
dvf_clean = dvf_clean.drop_duplicates(
    subset=['Date mutation','Valeur fonciere','Code departement','Code commune','Voie'], keep='first'
)
print("Apres dedupliaction:",len(dvf_clean))

Apres dedupliaction: 884397

In [11]:
#Calculer le Prix au m^2
dvf_clean['prix_m2'] = dvf_clean['Valeur fonciere'] / dvf_clean['Surface reelle bati']
print(dvf_clean['prix_m2'].describe())

count    8.843970e+05
mean     4.261912e+03
std      5.619849e+04
min      1.379310e-03
25%      1.690076e+03
50%      2.625000e+03
75%      4.044444e+03
max      3.159091e+07
Name: prix_m2, dtype: float64

In [12]:
pd.options.display.float_format = '{:.2f}'.format

In [13]:
# filtrage sur une tranche entre 100 et 30000
dvf_filtres = dvf_clean[
    (dvf_clean['prix_m2'] >= 100) & (dvf_clean['prix_m2'] <= 30000 )
]

print(dvf_filtres['prix_m2'].describe())

count   876991.00
mean      3352.07
std       2786.23
min        100.00
25%       1697.94
50%       2625.00
75%       4025.72
max      30000.00
Name: prix_m2, dtype: float64

In [14]:
# la reconstruction du code INSEE dans tableau dvf
dvf_filtres['code_insee'] = (
    dvf_filtres['Code departement'].astype(str).str.zfill(2) + 
    dvf_filtres['Code commune'].astype(str).str.zfill(3)
 )
dvf_filtres[['Code departement','Code commune', 'code_insee']].head()

C:\Users\anass\AppData\Local\Temp\ipykernel_24768\4257528176.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_filtres['code_insee'] = (

   Code departement  Code commune code_insee
2                01           158      01158
5                01           257      01257
9                01            65      01065
18               01           173      01173
21               01            28      01028

In [15]:
# preparer la cle dans la table des loyers
loyers['code_insee'] = loyers['INSEE_C'].astype(str).str.zfill(5)

In [16]:
# Fusion entre deux tableaux
dvf_enrichi = pd.merge(
    dvf_filtres,
    loyers[['code_insee', 'loypredm2']],
    on='code_insee',
    how='inner'
)

print("Nombre de lignes après jointure :", len(dvf_enrichi))
dvf_enrichi[['code_insee', 'prix_m2', 'loypredm2']].head()

Nombre de lignes après jointure : 867530

  code_insee  prix_m2         loypredm2
0      01158  4216.22    20,06635999994
1      01257  2068.97  12,6913360282741
2      01065  2578.95  10,2166999158374
3      01173  5228.57  19,9021436251448
4      01028  3105.26  12,5482292152302

In [17]:
# Convertir loypredm2 en vrai nombre (float)
dvf_enrichi['loypredm2'] = dvf_enrichi['loypredm2'].astype(str).str.replace(',','.',regex=False)
dvf_enrichi['loypredm2'] = pd.to_numeric(dvf_enrichi['loypredm2'], errors='coerce')

In [18]:
# Calculer le Rendement Locatif Brut (%)
dvf_enrichi['rendement_brut'] = (dvf_enrichi['loypredm2'] * 12 / dvf_enrichi['prix_m2'])*100
print(dvf_enrichi['rendement_brut'].describe())

count   867530.00
mean         7.26
std          7.84
min          0.25
25%          4.37
50%          5.75
75%          7.90
max        434.90
Name: rendement_brut, dtype: float64

Enquêter sur les "fausses pépites"  
affichons les 5 biens ayant le rendement le plus élevé

In [19]:
dvf_enrichi = dvf_enrichi.sort_values(by='rendement_brut',ascending=False)
dvf_enrichi[['Commune', 'Type local', 'Valeur fonciere', 'Surface reelle bati', 'prix_m2', 'loypredm2', 'rendement_brut']].head(5)

,Commune,Type local,Valeur fonciere,Surface reelle bati,prix_m2,loypredm2,rendement_brut
866288,PARIS 07,Appartement,1000.00,10.00,100.00,36.24,434.90
862723,PARIS 05,Appartement,5000.00,49.00,102.04,34.32,403.65
840825,PARIS 03,Appartement,5000.00,47.00,106.38,34.83,392.88
838445,PARIS 01,Appartement,13125.00,126.00,104.17,33.17,382.17
866955,PARIS 07,Appartement,20000.00,175.00,114.29,36.24,380.54

In [20]:
# calcul d'une médiane par groupe :
dvf_enrichi['prix_m2_median_commune'] = dvf_enrichi.groupby(['code_insee', 'Type local'])['prix_m2'].transform('median')
dvf_enrichi[['code_insee','Commune','prix_m2','prix_m2_median_commune']]

       code_insee              Commune  prix_m2  prix_m2_median_commune
866288      75107             PARIS 07   100.00                13954.55
862723      75105             PARIS 05   102.04                11797.75
840825      75103             PARIS 03   106.38                11914.70
838445      75101             PARIS 01   104.17                12102.63
866955      75107             PARIS 07   114.29                13954.55
...           ...                  ...      ...                     ...
64608       10070     CELLES SUR OURCE 24642.86                24642.86
598315      72262       LOIR EN VALLEE 27000.00                 1231.88
509515      61230  LONGNY LES VILLAGES 29914.53                 1576.09
405097      48104            NASBINALS 28733.33                 1708.33
148667      21291                GENAY 28400.00                16071.43

[867530 rows x 4 columns]

In [21]:
# Compter le nombre de ventes par commune et type de bien
dvf_enrichi['nb_ventes_commune_type'] = dvf_enrichi.groupby(['code_insee', 'Type local'])['prix_m2'].transform('count')

# Regardons à quoi ressemble la distribution du nombre de ventes
print(dvf_enrichi['nb_ventes_commune_type'].describe())

count   867530.00
mean       553.80
std       1192.05
min          1.00
25%         25.00
50%         92.00
75%        455.00
max       7587.00
Name: nb_ventes_commune_type, dtype: float64

In [22]:
# Calcul d'une remise ou décote en % 
dvf_enrichi['decote_pct'] = ((dvf_enrichi['prix_m2_median_commune'] - dvf_enrichi['prix_m2']) / dvf_enrichi['prix_m2_median_commune']) * 100
dvf_enrichi[['code_insee','Commune','prix_m2','prix_m2_median_commune','decote_pct']].head()

       code_insee   Commune  prix_m2  prix_m2_median_commune  decote_pct
866288      75107  PARIS 07   100.00                13954.55       99.28
862723      75105  PARIS 05   102.04                11797.75       99.14
840825      75103  PARIS 03   106.38                11914.70       99.11
838445      75101  PARIS 01   104.17                12102.63       99.14
866955      75107  PARIS 07   114.29                13954.55       99.18

 Filtrer et isoler les pépites
  créer un nouveau DataFrame appelé pepites

In [23]:
pepites = dvf_enrichi[
    (dvf_enrichi['decote_pct']>=15) & (dvf_enrichi['decote_pct']<=40)
     & (dvf_enrichi['rendement_brut']>=7) & (dvf_enrichi['rendement_brut']<=15) 
     & (dvf_enrichi['Surface reelle bati']>=15) & (dvf_enrichi['nb_ventes_commune_type'] >= 10)

]
print("pepites trouvees :", len(pepites))
pepites [['Commune', 'Type local', 'Surface reelle bati', 'Valeur fonciere', 'prix_m2', 'prix_m2_median_commune', 'decote_pct', 'rendement_brut']]

pepites trouvees : 94811

,Commune,Type local,Surface reelle bati,Valeur fonciere,prix_m2,prix_m2_median_commune,decote_pct,rendement_brut
682151,NESLE,Maison,60.00,48000.00,800.00,1035.10,22.71,15.00
361509,SAINT-CHAMOND,Appartement,89.00,73500.00,825.84,1330.38,37.92,15.00
81475,MARSEILLE 3EME,Appartement,53.00,60000.00,1132.08,1750.00,35.31,15.00
679131,PLAINE-ET-VALLEES,Maison,142.00,95000.00,669.01,891.67,24.97,15.00
513763,ST-POL-SUR-TERNOISE,Maison,100.00,78000.00,780.00,1132.03,31.10,15.00
...,...,...,...,...,...,...,...,...
262738,ARTIGUES-PRES-BORDEAUX,Maison,138.00,331000.00,2398.55,3139.79,23.61,7.00
268968,NAUJAC-SUR-MER,Maison,102.00,203400.00,1994.12,2434.96,18.10,7.00
675069,VERSAILLES,Appartement,90.00,370000.00,4111.11,6428.57,36.05,7.00
533942,JOZE,Maison,162.00,279000.00,1722.22,2356.53,26.92,7.00
571437,LYON 9EME,Appartement,97.00,262200.00,2703.09,3804.43,28.95,7.00

sauvegarder DataFrame pepites dans un fichier CSV, on utilise la méthode .to_csv().

In [24]:
colonnes_utiles = ['Commune', 'Code postal', 'Code departement', 'code_insee' , 'Date mutation', 'Type local', 'Surface reelle bati', 'Nombre pieces principales' , 'Valeur fonciere', 'prix_m2', 'prix_m2_median_commune', 'decote_pct', 'rendement_brut','nb_ventes_commune_type']
pepites[colonnes_utiles].to_csv(r"C:\Users\anass\Desktop\immoscout-analytics\data\processed\resultat.csv", index=False)

Faire un rapide sanity check sur un échantillon de 10 premières

In [25]:
pepites[colonnes_utiles].head(5)

,Commune,Code postal,Code departement,code_insee,Date mutation,Type local,Surface reelle bati,Nombre pieces principales,Valeur fonciere,prix_m2,prix_m2_median_commune,decote_pct,rendement_brut,nb_ventes_commune_type
682151,NESLE,80190.00,80,80585,14/01/2025,Maison,60.00,4.00,48000.00,800.00,1035.10,22.71,15.00,28
361509,SAINT-CHAMOND,42400.00,42,42207,31/12/2025,Appartement,89.00,4.00,73500.00,825.84,1330.38,37.92,15.00,234
81475,MARSEILLE 3EME,13003.00,13,13203,17/04/2025,Appartement,53.00,4.00,60000.00,1132.08,1750.00,35.31,15.00,603
679131,PLAINE-ET-VALLEES,79100.00,79,79196,10/07/2025,Maison,142.00,6.00,95000.00,669.01,891.67,24.97,15.00,39
513763,ST-POL-SUR-TERNOISE,62130.00,62,62767,09/12/2025,Maison,100.00,4.00,78000.00,780.00,1132.03,31.10,15.00,62

In [26]:
dvf[dvf['Commune'] == 'JOZE'].head(10)

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
2333403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/02/2025,Vente,"39316,20",NaN,NaN,NaN,B008,LES BONNABIOUX,63350.00,JOZE,63,180,NaN,ZT,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,PA,NaN,6708.00
2333404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/02/2025,Vente,"39316,20",NaN,NaN,NaN,B008,LES BONNABIOUX,63350.00,JOZE,63,180,NaN,ZT,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,PA,NaN,3954.00
2334054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,21/02/2025,Vente,"36300,00",NaN,NaN,NaN,B094,PRE MARAS,63350.00,JOZE,63,180,NaN,ZV,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,T,NaN,9455.00
2334055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,21/02/2025,Vente,"36300,00",NaN,NaN,NaN,B094,PRE MARAS,63350.00,JOZE,63,180,NaN,ZV,189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,T,NaN,33350.00
2335878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,28/02/2025,Vente,"60000,00",NaN,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,1155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,AB,NaN,510.00
2339552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,08/04/2025,Vente,"70000,00",NaN,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,1188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,T,NaN,38.00
2339553,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,08/04/2025,Vente,"70000,00",NaN,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,1191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,P,NaN,571.00
2341229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/04/2025,Vente,"29260,00",NaN,NaN,NaN,B078,LES MARTINES,63350.00,JOZE,63,180,NaN,YB,176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,AB,NaN,916.00
2341230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/04/2025,Vente,"29260,00",NaN,NaN,NaN,B078,LES MARTINES,63350.00,JOZE,63,180,NaN,YB,178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,AB,NaN,32.00
2341231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/04/2025,Vente,"29260,00",NaN,NaN,NaN,B078,LES MARTINES,63350.00,JOZE,63,180,NaN,YB,180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,97.00

In [27]:
dvf[(dvf['Commune'] == 'JOZE') & (dvf['Valeur fonciere'] == '279000,00')]

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
2362321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,S,NaN,900.00
2362322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,T,NaN,2372.00
2362323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,T,NaN,2372.00
2362324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.00,Maison,NaN,162.00,6.00,T,NaN,2372.00
2362325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,T,NaN,2372.00
2362326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.00,Maison,NaN,162.00,6.00,AG,NaN,825.00
2362327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,AG,NaN,825.00
2362328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,AG,NaN,825.00
2362329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,AG,NaN,825.00
2362330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.00,Maison,NaN,162.00,6.00,J,NaN,890.00
2362331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,J,NaN,890.00
2362332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,J,NaN,890.00
2362333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,J,NaN,890.00
2362334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.00,Maison,NaN,162.00,6.00,S,NaN,900.00
2362335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,S,NaN,900.00
2362336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/09/2025,Vente,"279000,00",5002.00,NaN,NaN,B070,JOZE,63350.00,JOZE,63,180,NaN,AP,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.00,Dépendance,NaN,0.00,0.00,S,NaN,900.00