In [4]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

https://www.data.gouv.fr/datasets/demandes-de-valeurs-foncieres?resource_id=087ec735-74fd-48a7-a82e-0b1cd3ea6fe9

In [5]:

# Charger les données
dvf = pd.read_csv(
    r"C:\Users\anass\Desktop\immoscout-analytics\data\raw\ValeursFoncieres-2025.txt",
    sep="|",
    low_memory=False
)



# Examiner les données DVF
print("DVF")
print(dvf.shape)
print(dvf.columns.tolist())
display(dvf.head())

DVF
(3714829, 43)
['Identifiant de document', 'Reference document', '1 Articles CGI', '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI', 'No disposition', 'Date mutation', 'Nature mutation', 'Valeur fonciere', 'No voie', 'B/T/Q', 'Type de voie', 'Code voie', 'Voie', 'Code postal', 'Commune', 'Code departement', 'Code commune', 'Prefixe de section', 'Section', 'No plan', 'No Volume', '1er lot', 'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot', '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot', 'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot', 'Nombre de lots', 'Code type local', 'Type local', 'Identifiant local', 'Surface reelle bati', 'Nombre pieces principales', 'Nature culture', 'Nature culture speciale', 'Surface terrain']

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,"468000,00",NaN,NaN,NaN,B078,FARGES,1550.0,FARGES,01,158,NaN,B,815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,78.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,"468000,00",454.0,NaN,RUE,0090,DE LA REPUBLIQUE,1550.0,FARGES,01,158,NaN,B,910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.0,Dépendance,NaN,0.0,0.0,S,NaN,133.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,"468000,00",454.0,NaN,RUE,0090,DE LA REPUBLIQUE,1550.0,FARGES,01,158,NaN,B,910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,111.0,5.0,S,NaN,133.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,"180000,00",NaN,NaN,NaN,B158,LE VILLAGE,1200.0,MONTANGES,01,257,NaN,AC,334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,46.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,"180000,00",NaN,NaN,NaN,B158,LE VILLAGE,1200.0,MONTANGES,01,257,NaN,AC,338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,17.0

https://www.data.gouv.fr/datasets/carte-des-loyers-indicateurs-de-loyers-dannonce-par-commune-en-2024?resource_id=4a6074fb-7d1f-437d-8cef-f033b2114fd1

In [6]:
## Examiner les données locatives
loyers = pd.read_csv(
    r"C:\Users\anass\Desktop\immoscout-analytics\data\raw\pred-app-mef-dhup.csv",
    sep=";",
    encoding="cp1252",
    low_memory=False
)
print("LOYERS")
print(loyers.shape)
print(loyers.columns.tolist())
display(loyers.head())

LOYERS
(34960, 13)
['id_zone', 'INSEE_C', 'LIBGEO', 'EPCI', 'DEP', 'REG', 'loypredm2', 'lwr.IPm2', 'upr.IPm2', 'TYPPRED', 'nbobs_com', 'nbobs_mail', 'R2_adj']

,id_zone,INSEE_C,LIBGEO,EPCI,DEP,REG,loypredm2,lwr.IPm2,upr.IPm2,TYPPRED,nbobs_com,nbobs_mail,R2_adj
0,1,86051,Champagné-le-Sec,200070035,86,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,0,1044,"0,719908446134695"
1,1,16136,La Faye,200043016,16,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,4,1044,"0,719908446134695"
2,1,16002,Les Adjots,200043016,16,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,2,1044,"0,719908446134695"
3,1,79150,Limalonges,200069755,79,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,3,1044,"0,719908446134695"
4,1,16104,Condac,200043016,16,75,"8,48108601820233","6,60248185247569","10,8942094284101",maille,11,1044,"0,719908446134695"

In [7]:
## Examiner les données locatives
communes = pd.read_csv(
    r"C:\Users\anass\Desktop\immoscout-analytics\data\raw\v_commune_2026.csv",
    sep=",",
    low_memory=False
)
print("communes")
print(communes.shape)
print(communes.columns.tolist())
display(communes.head())

communes
(37496, 12)
['TYPECOM', 'COM', 'REG', 'DEP', 'CTCD', 'ARR', 'TNCC', 'NCC', 'NCCENR', 'LIBELLE', 'CAN', 'COMPARENT']

,TYPECOM,COM,REG,DEP,CTCD,ARR,TNCC,NCC,NCCENR,LIBELLE,CAN,COMPARENT
0,COM,01001,84.0,01,01D,012,5,ABERGEMENT CLEMENCIAT,Abergement-Clémenciat,L'Abergement-Clémenciat,0108,NaN
1,COM,01002,84.0,01,01D,011,5,ABERGEMENT DE VAREY,Abergement-de-Varey,L'Abergement-de-Varey,0101,NaN
2,COM,01004,84.0,01,01D,011,1,AMBERIEU EN BUGEY,Ambérieu-en-Bugey,Ambérieu-en-Bugey,0101,NaN
3,COM,01005,84.0,01,01D,012,1,AMBERIEUX EN DOMBES,Ambérieux-en-Dombes,Ambérieux-en-Dombes,0122,NaN
4,COM,01006,84.0,01,01D,011,1,AMBLEON,Ambléon,Ambléon,0104,NaN

In [8]:
#compter le nbr de ventes par types de bien
dvf['Type local'].value_counts(dropna=False)

Type local
NaN                                         1469244
Dépendance                                   996489
Maison                                       619955
Appartement                                  512979
Local industriel. commercial ou assimilé     116162
Name: count, dtype: int64

In [9]:
# 1. on conserve (maisons et apparts)
dvf_logements = dvf[dvf['Type local'].isin(['Maison', 'Appartement'])]

In [10]:
# 2.  affiche les lignes restantes 
print("nombre de transaction d'habitations :",len(dvf_logements))

nombre de transaction d'habitations : 1132934

In [11]:
# Combien d'habitations ont un prix manquant ou à 0 ?
dvf_logements['Valeur fonciere'] = (
    dvf_logements['Valeur fonciere']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

dvf_logements['Valeur fonciere'] = pd.to_numeric(
    dvf_logements['Valeur fonciere'],
    errors='coerce'
)
prix_invalides = dvf_logements['Valeur fonciere'].isna() | (dvf_logements['Valeur fonciere'] <= 0)

# Combien d'habitations ont une surface manquante ou à 0 ?
dvf_logements['Surface reelle bati'] = (
    dvf_logements['Surface reelle bati']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

dvf_logements['Surface reelle bati'] = pd.to_numeric(
    dvf_logements['Surface reelle bati'],
    errors='coerce'
)

surfaces_invalides = dvf_logements['Surface reelle bati'].isna() | (dvf_logements['Surface reelle bati'] <= 0)

print("Logements sans prix valide :", prix_invalides.sum())
print("Logements sans surface valide :", surfaces_invalides.sum())

C:\Users\anass\AppData\Local\Temp\ipykernel_7004\1414518120.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_logements['Valeur fonciere'] = (
C:\Users\anass\AppData\Local\Temp\ipykernel_7004\1414518120.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_logements['Valeur fonciere'] = pd.to_numeric(
C:\Users\anass\AppData\Local\Temp\ipykernel_7004\1414518120.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_logements['Surface reelle bati'] = (

Logements sans prix valide : 10448
Logements sans surface valide : 97

C:\Users\anass\AppData\Local\Temp\ipykernel_7004\1414518120.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_logements['Surface reelle bati'] = pd.to_numeric(

In [12]:
# nettoyage des donnees
dvf_clean = dvf_logements[
    (dvf_logements['Valeur fonciere'] > 0) &
    (dvf_logements['Surface reelle bati'] > 0)
]

print(len(dvf_clean))

1122389

In [13]:
#Calculer le Prix au m^2
dvf_clean['prix_m2'] = dvf_clean['Valeur fonciere'] / dvf_clean['Surface reelle bati']
print(dvf_clean['prix_m2'].describe())

count    1.122389e+06
mean     1.788748e+04
std      1.726751e+05
min      1.379310e-03
25%      1.730769e+03
50%      2.740292e+03
75%      4.560377e+03
max      3.159091e+07
Name: prix_m2, dtype: float64

C:\Users\anass\AppData\Local\Temp\ipykernel_7004\1225716018.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_clean['prix_m2'] = dvf_clean['Valeur fonciere'] / dvf_clean['Surface reelle bati']

In [14]:
pd.options.display.float_format = '{:.2f}'.format

In [15]:
# filtrage sur une tranche entre 100 et 30000
dvf_filtres = dvf_clean[
    (dvf_clean['prix_m2'] >= 100) & (dvf_clean['prix_m2'] <= 30000 )
]

print(dvf_filtres['prix_m2'].describe())

count   1072286.00
mean       3690.21
std        3557.13
min         100.00
25%        1712.96
50%        2666.67
75%        4250.00
max       30000.00
Name: prix_m2, dtype: float64

In [16]:
# la reconstruction du code INSEE dans tableau dvf
dvf_filtres['code_insee'] = (
    dvf_filtres['Code departement'].astype(str).str.zfill(2) + 
    dvf_filtres['Code commune'].astype(str).str.zfill(3)
 )
dvf_filtres[['Code departement','Code commune', 'code_insee']].head()

C:\Users\anass\AppData\Local\Temp\ipykernel_7004\4257528176.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dvf_filtres['code_insee'] = (

   Code departement  Code commune code_insee
2                01           158      01158
5                01           257      01257
9                01            65      01065
14               01            65      01065
18               01           173      01173

In [17]:
# preparer la cle dans la table des loyers
loyers['code_insee'] = loyers['INSEE_C'].astype(str).str.zfill(5)

In [18]:
# Fusion entre deux tableaux
dvf_enrichi = pd.merge(
    dvf_filtres,
    loyers[['code_insee', 'loypredm2']],
    on='code_insee',
    how='inner'
)

print("Nombre de lignes après jointure :", len(dvf_enrichi))
dvf_enrichi[['code_insee', 'prix_m2', 'loypredm2']].head()

Nombre de lignes après jointure : 1059884

  code_insee  prix_m2         loypredm2
0      01158  4216.22    20,06635999994
1      01257  2068.97  12,6913360282741
2      01065  2578.95  10,2166999158374
3      01065  2578.95  10,2166999158374
4      01173  5228.57  19,9021436251448

In [19]:
# Convertir loypredm2 en vrai nombre (float)
dvf_enrichi['loypredm2'] = dvf_enrichi['loypredm2'].astype(str).str.replace(',','.',regex=False)
dvf_enrichi['loypredm2'] = pd.to_numeric(dvf_enrichi['loypredm2'], errors='coerce')

In [20]:
# Calculer le Rendement Locatif Brut (%)
dvf_enrichi['rendement_brut'] = (dvf_enrichi['loypredm2'] * 12 / dvf_enrichi['prix_m2'])*100
print(dvf_enrichi['rendement_brut'].describe())

count   1059884.00
mean          7.03
std           7.99
min           0.25
25%           4.12
50%           5.58
75%           7.73
max         434.90
Name: rendement_brut, dtype: float64

Enquêter sur les "fausses pépites"  
affichons les 5 biens ayant le rendement le plus élevé

In [21]:
dvf_enrichi = dvf_enrichi.sort_values(by='rendement_brut',ascending=False)
dvf_enrichi[['Commune', 'Type local', 'Valeur fonciere', 'Surface reelle bati', 'prix_m2', 'loypredm2', 'rendement_brut']].head(5)

,Commune,Type local,Valeur fonciere,Surface reelle bati,prix_m2,loypredm2,rendement_brut
1058565,PARIS 07,Appartement,1000.00,10.00,100.00,36.24,434.90
1054840,PARIS 05,Appartement,5000.00,49.00,102.04,34.32,403.65
1031900,PARIS 03,Appartement,5000.00,47.00,106.38,34.83,392.88
1029392,PARIS 01,Appartement,13125.00,126.00,104.17,33.17,382.17
1059276,PARIS 07,Appartement,20000.00,175.00,114.29,36.24,380.54

In [28]:
# calcul d'une médiane par groupe :
dvf_enrichi['prix_m2_median_commune'] = dvf_enrichi.groupby('code_insee')['prix_m2'].transform('median')
dvf_enrichi[['code_insee','Commune','prix_m2','prix_m2_median_commune']]

        code_insee                 Commune  prix_m2  prix_m2_median_commune
1058565      75107                PARIS 07   100.00                13987.34
1054840      75105                PARIS 05   102.04                11853.66
1031900      75103                PARIS 03   106.38                12000.00
1029392      75101                PARIS 01   104.17                12157.69
1059276      75107                PARIS 07   114.29                13987.34
...            ...                     ...      ...                     ...
540639       53221  SAINT-GEORGES-SUR-ERVE 26786.25                 1306.12
501591       48104               NASBINALS 28733.33                 2886.96
199820       23071                   CROZE 28703.70                16241.50
179911       21291                   GENAY 28400.00                 3360.06
179909       21291                   GENAY 28400.00                 3360.06

[1059884 rows x 4 columns]

In [34]:
# Calcul d'une remise ou décote en % 
dvf_enrichi['decote_pct'] = ((dvf_enrichi['prix_m2_median_commune'] - dvf_enrichi['prix_m2']) / dvf_enrichi['prix_m2_median_commune']) * 100
dvf_enrichi[['code_insee','Commune','prix_m2','prix_m2_median_commune','decote_pct']].head()

        code_insee   Commune  prix_m2  prix_m2_median_commune  decote_pct
1058565      75107  PARIS 07   100.00                13987.34       99.29
1054840      75105  PARIS 05   102.04                11853.66       99.14
1031900      75103  PARIS 03   106.38                12000.00       99.11
1029392      75101  PARIS 01   104.17                12157.69       99.14
1059276      75107  PARIS 07   114.29                13987.34       99.18

 Filtrer et isoler les pépites
  créer un nouveau DataFrame appelé pepites

In [41]:
pepites = dvf_enrichi[
    (dvf_enrichi['decote_pct']>=15) & (dvf_enrichi['decote_pct']<=40)
     & (dvf_enrichi['rendement_brut']>=7) & (dvf_enrichi['rendement_brut']<=15) & (dvf_enrichi['Surface reelle bati']>=15)
]
print("pepites trouvees :", len(pepites))
pepites [['Commune', 'Type local', 'Surface reelle bati', 'Valeur fonciere', 'prix_m2', 'prix_m2_median_commune', 'decote_pct', 'rendement_brut']]

pepites trouvees : 127417

,Commune,Type local,Surface reelle bati,Valeur fonciere,prix_m2,prix_m2_median_commune,decote_pct,rendement_brut
836885,PLAINE-ET-VALLEES,Maison,142.00,95000.00,669.01,875.00,23.54,15.00
723801,SAINT-SAUVEUR,Appartement,90.00,57000.00,633.33,1021.05,37.97,15.00
636799,ST-POL-SUR-TERNOISE,Maison,100.00,78000.00,780.00,1215.69,35.84,15.00
573960,IMPHY,Appartement,17.00,11000.00,647.06,1014.49,36.22,15.00
611968,LANDRECIES,Maison,92.00,63000.00,684.78,1094.67,37.44,15.00
...,...,...,...,...,...,...,...,...
661616,JOZE,Maison,162.00,279000.00,1722.22,2286.11,24.67,7.00
661618,JOZE,Maison,162.00,279000.00,1722.22,2286.11,24.67,7.00
661615,JOZE,Maison,162.00,279000.00,1722.22,2286.11,24.67,7.00
661617,JOZE,Maison,162.00,279000.00,1722.22,2286.11,24.67,7.00
706332,LYON 9EME,Appartement,97.00,262200.00,2703.09,3846.15,29.72,7.00